In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Data/1980_title_publ_inventor/1980_title_publ_inventor.csv')
df

,title.en,inventor,publication.date,publication.number,publication.country,applicant,representative.name,representative.address,representative.city,representative.country,application.number,application.filing_date
0,A work table with a guard device for a motor-d...,"[{'name': 'Gjerde, Arne', 'country': 'NO', 'ci...",19800206,7796,EP,[{'country': 'NO'}],"Copp, David Christopher",Dummett Copp & Co.\n25 The Square\nMartlesham ...,Ipswich\nSuffolk IP5 7SL,GB,79301474.7,19790724
1,Method and plant for collecting of oil floatin...,"[{'name': 'Garin, Gert', 'country': 'SE', 'cit...",19800206,7891,EP,"[{'country': 'SE'}, {'country': 'SE'}]","Holmqvist, Lars J.H.","Albihn Holmqvist AB,\nBox 4289",203 14 Malmö 4,SE,79850066.6,19790706
2,"Skin treatment compositions, process for their...","[{'name': 'Alderson, Susan Glenys', 'country':...",19800206,7785,EP,"[{'country': 'GB'}, {'country': 'NL'}]","Tonge, Robert James",UNILEVER PLC\nPatent Division\nColworth House...,Bedford MK44 1LQ,GB,79301447.3,19790720
3,Safety circuit for a potentially dangerous mac...,"[{'name': 'Dieterle, Gerhard', 'country': 'DE'...",19800206,7420,EP,[{'country': 'DE'}],"Manitz, Gerhart, Dipl.-Phys. Dr.","Manitz, Finsterwald & Rotermund\nPatentanwälte...",D-80506 München,DE,79101936.7,19790613
4,Apparatus for wire stripping,"[{'name': 'Bieganski, Zdzislaw', 'country': 'G...",19800206,7699,EP,[{'country': 'GB'}],"Hands, Horace Geoffrey",GEORGE FUERY & CO\nWhitehall Chambers\n23 Colm...,Birmingham B3 2BL,GB,79301175.0,19790619
...,...,...,...,...,...,...,...,...,...,...,...,...
6747,Liquid phase chemical process with separation ...,"[{'name': 'Wood, Laurie', 'country': 'GB', 'ci...",19800903,14802,EP,[{'country': 'GB'}],"Martin, David Lincoln",Imperial Chemical Industries PLC\nLegal Depart...,"Welwyn Garden City\nHerts, AL7 1HD",GB,79302840.8,19791210
6748,Olefine polymerization catalyst and use thereof,"[{'name': 'Gavens, Paul David', 'country': 'GB...",19800903,15048,EP,[{'country': 'GB'}],"James, David Gomer",Imperial Chemical Industries PLC\nLegal Depart...,"Welwyn Garden City\nHerts, AL7 1HD",GB,80300098.3,19800110
6749,Single cell protein and its production,"[{'name': 'Talbot, Colin John', 'country': 'GB...",19800903,15082,EP,[{'country': 'GB'}],"Aufflick, James Neil",Imperial Chemical Industries PLC\nLegal Depart...,"Welwyn Garden City\nHerts, AL7 1HD",GB,80300287.2,19800131
6750,Tri-iodoalkenyl esters of N-substituted carbam...,"[{'name': 'Gazzard, Edward George', 'country':...",19800903,15044,EP,[{'country': 'GB'}],"Pugsley, Roger Graham",ICI Group Patents Services Dept.\nPO Box 6\nSh...,"Welwyn Garden City\nHerts, AL7 1HD",GB,80300044.7,19800104
6751,Preparation of biphenol by the oxidative coupl...,"[{'name': 'Earley, Roger Alan', 'country': 'US...",19800903,15104,EP,[{'country': 'US'}],"Jones, Martin",Imperial Chemical Industries PLC\nLegal Depart...,"Welwyn Garden City\nHerts, AL7 1HD",GB,80300373.0,19800207

In [3]:
df_2 = pd.read_csv('../Data/1980_title_publ_inventor (1)/1980_title_publ_inventor.csv')
df_2

,title.en,publication.country,publication.number,publication.kind,publication.date,publication.language,inventor
0,Building elements and method of constructing a...,EP,20014,A2,19801210,EN,"[{'name': 'Robertson, Gordon MacDonald', 'addr..."
1,Esters of halogenated substituted cyclopropano...,EP,16513,A3,19801210,EN,"[{'name': 'Bentley, Philip David', 'address': ..."
2,"Recognins, their chemoreciprocals, target atta...",EP,15755,A3,19801210,EN,"[{'name': 'Bogoch, Samuel, Dr.', 'address': ''..."
3,Gem-bis (hydroxymethyl) alcohols and mixtures ...,EP,17503,A3,19801210,EN,"[{'name': 'Rogier, Edgar R.', 'address': '', '..."
4,Novel process for the manufacture of thiophene...,EP,19788,A2,19801210,EN,"[{'name': 'Baggioline, Enrico Giuseppe', 'addr..."
...,...,...,...,...,...,...,...
6747,Lubricating composition and method for making ...,EP,13773,A1,19800806,EN,"[{'name': 'Lankamp, Herman, Dr.', 'address': '..."
6748,"Deuterated isoflurane, its use as an anestheti...",EP,13921,A1,19800806,EN,"[{'name': 'McCarty, Leslie Paul', 'address': '..."
6749,Novel branched-chain monoalcohols and derivati...,EP,10808,A3,19800806,EN,"[{'name': 'Zeilstra, Jacobus Johannes', 'addre..."
6750,"Electrocatalyst, electrode comprising the elec...",EP,13572,A3,19800806,EN,"[{'name': 'Spaziante, Placido', 'address': '',..."
6751,A perfumed synthetic resin product and a metho...,EP,13688,A1,19800806,EN,"[{'name': 'Shibanai, Ichiro', 'address': 'No. ..."