# Load Data into DataBase

#### Load Libraries

In [1]:
import pandas as pd
import sqlite3
import joblib
import os
from tqdm import tqdm
import os

# set working directory
os.chdir("/home/jovyan/dsp/")

## Patent Table

In [3]:
# crea SQLite database and establish connection
conn = sqlite3.connect('../Data/patent.db')
cursor = conn.cursor()

OperationalError: unable to open database file

In [2]:
# loop through all folders in patent_metadata and load data into database
metadata_folder = "../Data/patents_metadata/"
folders_all = os.listdir(metadata_folder)

df_metadata = pd.DataFrame()

for folder in folders_all:
    folder_path = os.path.join(metadata_folder, folder)
    if os.path.isdir(folder_path):
        files = os.listdir(folder_path)
        for file in files:
            if file.endswith('.csv'):
                file_path = os.path.join(folder_path, file)
                df = pd.read_csv(file_path)
                df_metadata = pd.concat([df_metadata, df], ignore_index=True)
                # df.to_sql('patent', conn, if_exists='append', index=False)

In [3]:
df_metadata.to_parquet('../Data/patent_metadata.parquet', index=False)

In [4]:
df_metadata.head()

,title.en,inventor,publication.date,publication.number,publication.country,applicant,representative.name,representative.address,representative.city,representative.country,application.number,application.filing_date
0,A work table with a guard device for a motor-d...,"[{'name': 'Gjerde, Arne', 'country': 'NO', 'ci...",19800206,7796,EP,[{'country': 'NO'}],"Copp, David Christopher",Dummett Copp & Co.\n25 The Square\nMartlesham ...,Ipswich\nSuffolk IP5 7SL,GB,79301474.7,19790724
1,Method and plant for collecting of oil floatin...,"[{'name': 'Garin, Gert', 'country': 'SE', 'cit...",19800206,7891,EP,"[{'country': 'SE'}, {'country': 'SE'}]","Holmqvist, Lars J.H.","Albihn Holmqvist AB,\nBox 4289",203 14 Malmö 4,SE,79850066.6,19790706
2,"Skin treatment compositions, process for their...","[{'name': 'Alderson, Susan Glenys', 'country':...",19800206,7785,EP,"[{'country': 'GB'}, {'country': 'NL'}]","Tonge, Robert James",UNILEVER PLC\nPatent Division\nColworth House...,Bedford MK44 1LQ,GB,79301447.3,19790720
3,Safety circuit for a potentially dangerous mac...,"[{'name': 'Dieterle, Gerhard', 'country': 'DE'...",19800206,7420,EP,[{'country': 'DE'}],"Manitz, Gerhart, Dipl.-Phys. Dr.","Manitz, Finsterwald & Rotermund\nPatentanwälte...",D-80506 München,DE,79101936.7,19790613
4,Apparatus for wire stripping,"[{'name': 'Bieganski, Zdzislaw', 'country': 'G...",19800206,7699,EP,[{'country': 'GB'}],"Hands, Horace Geoffrey",GEORGE FUERY & CO\nWhitehall Chambers\n23 Colm...,Birmingham B3 2BL,GB,79301175.0,19790619

In [4]:
# query to check data load into pandas dataframe
query = """
SELECT * FROM patent
where "publication.number" = 3587222
"""

res = cursor.execute(query)
res.fetchall()

[('LOWER VEHICLE-BODY STRUCTURE OF VEHICLE',
  "[{'name': 'Nakauchi, Shigeru', 'country': 'JP', 'city': 'Fuchu-cho, Aki-gun, Hiroshima 730-8670', 'address': 'c/o Mazda Motor Corporation\\n3-1, Shinchi,'}, {'name': 'Hanazaki, Masanobu', 'country': 'JP', 'city': 'Fuchu-cho, Aki-gun, Hiroshima 730-8670', 'address': 'c/o Mazda Motor Corporation\\n3-1, Shinchi,'}, {'name': 'Kimura, Toshio', 'country': 'JP', 'city': 'Fuchu-cho, Aki-gun, Hiroshima 730-8670', 'address': 'c/o Mazda Motor Corporation\\n3-1, Shinchi,'}, {'name': 'Kurokawa, Sho', 'country': 'JP', 'city': 'Fuchu-cho, Aki-gun, Hiroshima 730-8670', 'address': 'c/o Mazda Motor Corporation\\n3-1, Shinchi,'}, {'name': 'Sakaguchi, Kinya', 'country': 'JP', 'city': 'Fuchu-cho, Aki-gun, Hiroshima 730-8670', 'address': 'c/o Mazda Motor Corporation\\n3-1, Shinchi,'}, {'name': 'Satou, Kouki', 'country': 'JP', 'city': 'Fuchu-cho, Aki-gun, Hiroshima 730-8670', 'address': 'c/o Mazda Motor Corporation\\n3-1, Shinchi,'}, {'name': 'Yabumoto, Yosuke', 'country': 'JP', 'city': 'Minami-ku, Hiroshima, Hiroshima 734-0026', 'address': 'c/o Mazda Engineering & Technology Co., Ltd.\\n1-26, Niho 2-chome,'}, {'name': 'Matsubara, Hiroshi', 'country': 'JP', 'city': 'Minami-ku, Hiroshima, Hiroshima 734-0026', 'address': 'c/o Mazda Engineering & Technology Co., Ltd.\\n1-26, Niho 2-chome,'}, {'name': 'Izumi, Yohei', 'country': 'JP', 'city': 'Minami-ku, Hiroshima, Hiroshima 734-0026', 'address': 'c/o Mazda Engineering & Technology Co., Ltd.\\n1-26, Niho 2-chome,'}, {'name': 'Nomura, Kentaro', 'country': 'JP', 'city': 'Minami-ku, Hiroshima, Hiroshima 734-0026', 'address': 'c/o Mazda Engineering & Technology Co., Ltd.\\n1-26, Niho 2-chome,'}]",
  20200101,
  3587222,
  'EP',
  "[{'country': 'JP'}]",
  'Müller-Boré & Partner \nPatentanwälte PartG mbB',
  'Friedenheimer Brücke 21',
  '80639 München',
  'DE',
  19181102.5,
  20190619)]

In [29]:
df_check

,title.en,inventor,publication.date,publication.number,publication.country,applicant,representative.name,representative.address,representative.city,representative.country,application.number,application.filing_date
0,A work table with a guard device for a motor-d...,"[{'name': 'Gjerde, Arne', 'country': 'NO', 'ci...",19800206,7796,EP,[{'country': 'NO'}],"Copp, David Christopher",Dummett Copp & Co.\n25 The Square\nMartlesham ...,Ipswich\nSuffolk IP5 7SL,GB,79301474.7,19790724
1,Method and plant for collecting of oil floatin...,"[{'name': 'Garin, Gert', 'country': 'SE', 'cit...",19800206,7891,EP,"[{'country': 'SE'}, {'country': 'SE'}]","Holmqvist, Lars J.H.","Albihn Holmqvist AB,\nBox 4289",203 14 Malmö 4,SE,79850066.6,19790706
2,"Skin treatment compositions, process for their...","[{'name': 'Alderson, Susan Glenys', 'country':...",19800206,7785,EP,"[{'country': 'GB'}, {'country': 'NL'}]","Tonge, Robert James",UNILEVER PLC\nPatent Division\nColworth House...,Bedford MK44 1LQ,GB,79301447.3,19790720
3,Safety circuit for a potentially dangerous mac...,"[{'name': 'Dieterle, Gerhard', 'country': 'DE'...",19800206,7420,EP,[{'country': 'DE'}],"Manitz, Gerhart, Dipl.-Phys. Dr.","Manitz, Finsterwald & Rotermund\nPatentanwälte...",D-80506 München,DE,79101936.7,19790613
4,Apparatus for wire stripping,"[{'name': 'Bieganski, Zdzislaw', 'country': 'G...",19800206,7699,EP,[{'country': 'GB'}],"Hands, Horace Geoffrey",GEORGE FUERY & CO\nWhitehall Chambers\n23 Colm...,Birmingham B3 2BL,GB,79301175.0,19790619
...,...,...,...,...,...,...,...,...,...,...,...,...
95,A device for generating an electric output sig...,"[{'name': 'Claesson, Per-Göran', 'country': 'S...",19800206,7893,EP,[{'country': 'SE'}],"Lindblom, Erik J.",Flotthamn,150 23 Enhörna,SE,79850070.8,19790716
96,Method of making a stress free plastic article...,"[{'name': 'Garabedian, Armen', 'country': 'US'...",19800206,7321,EP,[{'country': 'US'}],"Wilhelms, Rolf E., Dr.","WILHELMS, KILIAN & PARTNER\nPatentanwälte\nEdu...",81541 München,DE,78100547.5,19780728
97,Process for the preparation of a polyurethane ...,"[{'name': 'Turner, Robert Burton', 'country': ...",19800206,7484,EP,[{'country': 'US'}],"Weickmann, Heinrich, Dipl.-Ing.","Patentanwälte\nH. Weickmann, Dr. K. Fincke\nF....",81635 München,DE,79102268.4,19790704
98,New metal plastic laminates from polyolefin co...,"[{'name': 'Brachman, Armand E.', 'country': 'U...",19800206,7639,EP,[{'country': 'US'}],"Weickmann, Heinrich, Dipl.-Ing.","Patentanwälte\nH. Weickmann, Dr. K. Fincke\nF....",81635 München,DE,79102688.3,19790727
99,Handling apparatus for dual in-line packed (DI...,"[{'name': 'Boissicat, Claude M.', 'country': '...",19800206,7650,EP,[{'country': 'US'}],"Noz, Franciscus Xaverius, Ir.","World Trade Center,\nP. Petersstraat 160",5612 LV Eindhoven,NL,79200246.1,19790519

## Patent to IPC Mapping Table

In [18]:
conn = sqlite3.connect('data/patent.db')
cursor = conn.cursor()

cursor.execute("DROP TABLE IF EXISTS patent_ipc")

cursor.execute("""
CREATE TABLE patent_ipc (
    patent_id TEXT,
    ipc_code TEXT,
    YEAR INTEGER
);
""")

In [ ]:
data_test = joblib.load('data/embeddings/by_year/embeddings_2005.pkl')

In [15]:
data_id = {}

for patent in tqdm(data_test.keys()):
    id = patent.split('_')[0]
    data_id[id] = data_test[patent]

100%|██████████| 28/28 [00:00<00:00, 253104.55it/s]

In [ ]:
for year in tqdm(range(1980, 2024), desc="Years"):
    print(f"Processing year: {year}")
    embedding_file = f'data/embeddings/by_year/embeddings_{year}.pkl'
    data = joblib.load(embedding_file)

    data_id = {}
    
    for patent in data.keys():
        id = patent.split('_')[0]
        data_id[id] = data[patent]
        
    for patent_id, items in data_id.items():
        for ipc_code, embedding in items.items():
            insert_query = """
            INSERT INTO patent_ipc (patent_id, ipc_code, year)
            VALUES (?, ?, ?);
            """
            cursor.execute(insert_query, (patent_id, ipc_code, year))

conn.commit()

Years:   0%|          | 0/44 [00:00<?, ?it/s]

Processing year: 1980
Processing year: 1981
Processing year: 1982
Processing year: 1983
Processing year: 1984
Processing year: 1985
Processing year: 1986
Processing year: 1987
Processing year: 1988
Processing year: 1989
Processing year: 1990
Processing year: 1991
Processing year: 1992
Processing year: 1993
Processing year: 1994
Processing year: 1995
Processing year: 1996
Processing year: 1997
Processing year: 1998
Processing year: 1999
Processing year: 2000
Processing year: 2001
Processing year: 2002
Processing year: 2003
Processing year: 2004
Processing year: 2005
Processing year: 2006

Years:  61%|██████▏   | 27/44 [00:04<00:02,  5.69it/s]

Processing year: 2007

Years:  64%|██████▎   | 28/44 [00:09<00:06,  2.47it/s]

Processing year: 2008

Years:  66%|██████▌   | 29/44 [00:14<00:10,  1.42it/s]

Processing year: 2009

Years:  68%|██████▊   | 30/44 [00:19<00:14,  1.05s/it]

Processing year: 2010

Years:  70%|███████   | 31/44 [00:23<00:19,  1.46s/it]

Processing year: 2011

Years:  73%|███████▎  | 32/44 [00:29<00:24,  2.08s/it]

Processing year: 2012

Years:  75%|███████▌  | 33/44 [00:35<00:29,  2.71s/it]

Processing year: 2013

Years:  77%|███████▋  | 34/44 [00:41<00:33,  3.30s/it]

Processing year: 2014

Years:  80%|███████▉  | 35/44 [00:47<00:34,  3.86s/it]

Processing year: 2015

Years:  82%|████████▏ | 36/44 [00:53<00:34,  4.32s/it]

Processing year: 2016

Years:  84%|████████▍ | 37/44 [00:59<00:33,  4.78s/it]

Processing year: 2017

Years:  86%|████████▋ | 38/44 [01:06<00:32,  5.34s/it]

Processing year: 2018

Years:  89%|████████▊ | 39/44 [01:14<00:30,  6.00s/it]

Processing year: 2019

Years:  91%|█████████ | 40/44 [01:22<00:27,  6.75s/it]

Processing year: 2020

Years:  93%|█████████▎| 41/44 [01:32<00:22,  7.48s/it]

Processing year: 2021

Years:  95%|█████████▌| 42/44 [01:40<00:15,  7.88s/it]

Processing year: 2022

Years:  98%|█████████▊| 43/44 [01:50<00:08,  8.24s/it]

Processing year: 2023

Years: 100%|██████████| 44/44 [01:59<00:00,  2.71s/it]

In [23]:
conn.close()

## Add Metadata

In [13]:
conn = sqlite3.connect('data/patent.db')
cur = conn.cursor()

In [ ]:
df_metadata = pd.read_parquet('data/patent_metadata.parquet')

2322650

In [9]:
df_metadata.columns

Index(['title.en', 'inventor', 'publication.date', 'publication.number',
       'publication.country', 'applicant', 'representative.name',
       'representative.address', 'representative.city',
       'representative.country', 'application.number',
       'application.filing_date'],
      dtype='object')

In [13]:
# rename columns
renames = {
    "representative.city": "rep_city",
    "representative.country": "rep_country",
    "representative.name": "rep_name",
    "representative.address": "rep_address",  
    "application.number": "app_number",
    "application.filing_date": "app_date",
    "publication.number": "id",
    "publication.date": "pub_date",
    "publication.country": "pub_country",
    "title.en": "title"
}

df_metadata.rename(columns=renames, inplace=True)

# convert pub_date to datetime
df_metadata['pub_date'] = pd.to_datetime(df_metadata['pub_date'], format='%Y%m%d', errors='coerce')

In [15]:
df_metadata.to_sql('patent', conn, if_exists='replace', index=False)

2322650

In [21]:
# test sql load
query = """
SELECT count(patent_id) FROM patent_ipc;
"""
df_check = pd.read_sql_query(query, conn)
df_check

   count(patent_id)
0           2328863

In [17]:
# filter by year
query = """
SELECT * FROM patent
WHERE strftime('%Y', pub_date) = '2020'
LIMIT 100;
"""
df_check = pd.read_sql_query(query, conn)
df_check

,title,inventor,pub_date,id,pub_country,applicant,rep_name,rep_address,rep_city,rep_country,app_number,app_date
0,LID FOR CONTAINERS WITH IMPROVED SEAL,"[{'name': 'BERROA GARCÍA, Javier', 'country': ...",2020-07-08 00:00:00,3677527,EP,"[{'country': 'ES'}, {'country': 'FR'}]","Herrero & Asociados, S.L.","Cedaceros, 1",28014 Madrid,ES,17909654.0,20170831
1,FUEL INJECTION DEVICE,"[{'name': 'MATSUYAMA, Ryusuke', 'country': 'JP...",2020-07-08 00:00:00,3677839,EP,[{'country': 'JP'}],"Dantz, Jan Henning",Loesenbeck - Specht - Dantz \nPatent- und Rech...,33602 Bielefeld,DE,17923335.8,20170828
2,BATTERY SYSTEM AND VEHICLE,"[{'name': 'KUWANO, Yuuki', 'country': 'JP', 'c...",2020-07-08 00:00:00,3677926,EP,"[{'country': 'JP'}, {'country': 'JP'}]",AWA Sweden AB,Junkersgatan 1,582 35 Linköping,SE,17923155.0,20170829
3,"METHOD FOR PRODUCING FULVIC ACID SOLUTION, AND...","[{'name': 'MATSUI Saburo', 'country': 'JP', 'c...",2020-07-08 00:00:00,3677684,EP,[{'country': 'JP'}],Jacobacci Coralis Harle,"32, rue de l'Arcade",75008 Paris,FR,17923675.7,20171101
4,AIR CYLINDER FLUID CIRCUIT AND METHOD FOR DESI...,"[{'name': 'TAKADA, Yoshiyuki', 'country': 'JP'...",2020-07-08 00:00:00,3677794,EP,[{'country': 'JP'}],Keil & Schaafhausen Patentanwälte PartGmbB,Friedrichstraße 2-6,60323 Frankfurt am Main,DE,18849938.8,20180314
...,...,...,...,...,...,...,...,...,...,...,...,...
95,BAG,"[{'name': 'TANAKA, Daisuke', 'country': 'JP', ...",2020-07-08 00:00:00,3677529,EP,[{'country': 'JP'}],Beck Greener LLP,Fulwood House \n12 Fulwood Place,London WC1V 6HR,GB,18849976.8,20180830
96,SYSTEM FOR REDUCING PARTICULATE MATTER IN EXHA...,"[{'name': 'SON, Chang Soo', 'country': 'KR', '...",2020-07-08 00:00:00,3677759,EP,[{'country': 'KR'}],RatnerPrestia,Altheimer Eck 2,80331 München,DE,17922591.7,20170822
97,GADOBUTROL INTERMEDIATE AND GADOBUTROL PRODUCT...,"[{'name': 'LEE, Jae Yong', 'country': 'KR', 'c...",2020-07-08 00:00:00,3677574,EP,[{'country': 'KR'}],IPAZ,"Parc Les Algorithmes, Bâtiment Platon \nCS 700...",91192 Gif-sur-Yvette Cedex,FR,18851066.3,20180829
98,AUTONOMOUS COOLING VEST,"[{'name': 'Conti Filho, Gerson Tadeu', 'countr...",2020-07-08 00:00:00,3677138,EP,[{'country': 'BR'}],Cabinet Beaumont,"4, Place Robert Schuman \nB.P. 1529",38025 Grenoble Cedex 1,FR,18850901.2,20180417
99,REACTOR FOR A PROCESS OF ADVANCED COMBUSTION F...,"[{'name': 'Pereira Filho, Alberto Carlos', 'co...",2020-07-08 00:00:00,3677835,EP,[{'country': 'BR'}],"Díaz de Bustamante y Terminel, Isidro","Arcade & Asociados \nC/ Isabel Colbrand, 6-5th...",28050 Madrid,ES,18850319.7,20180903

In [18]:
# drop duplicate rows from patent_ipc table based on patent_id and ipc_code
cur.execute("""
DELETE FROM patent_ipc
WHERE rowid NOT IN (
    SELECT MIN(rowid)
    FROM patent_ipc
    GROUP BY patent_id, ipc_code
);
""")
conn.commit()